### ISSUE TITLE
Problem trying to use Initialize-CMSApplication and Get-CMSSite

### ISSUE THREAD

**Issue by awcoats** [clcrutch/posh-kentico#32]
Hi,  
I just discovered this project and I'm trying to use it.

I tried 
```
 Initialize-CMSApplication -ConnectionString "Data Source=blah blah " -WebRoot F:\Projects\KenticoCMS\CMS -Verbose
```

I then tried
```
Get-CMSSite
```

I have several Kentico databases on my localserver, but it seems to be listing sites from a K10 instance, not the K11 instance that is specified in database connection string used in the `Initialize-CMSApplication` command. 

Am I using the PowerShell commands in the correct way?

I really like this project - I'm really looking forward to trying to automate some tedious Kentico tasks. 

Regards,

Andrew

**Comment by clcrutch** [comment]
Hello Andrew,
That seems to be correct.  Please keep in mind, due to the way that the Kentico API works, once we initialize a connection, we will maintain that connection until PowerShell is closed.  You might find it beneficial to try a new instance.

I'd love to help you further troubleshoot this issue.

It sounds like you have multiple instances of Kentico installed in IIS.  These commands are intended to be run directly on the Kentico server.  If you elect not to initialize the application, we try to find an instance for you.  Is it possible that you attempted to run `Get-CMSSite` before you ran the initialize command?  If so, you might have initiated a connection to you K10 instance.

Once we find a Kentico instance, we store the information for that instance in a cache file `C:\ProgramData\PoshKentico\cache.json`,  You might try opening this file and see what's in it.

Let me know if this provides any more information.  Otherwise, I could try to help you troubleshoot it over email as well.

**Comment by clcrutch** [comment]
Closing this.  I can reopen if you continue to have this issue.
